class Texts(object):
    def intro():
        print(
            "¡Welcome to Pyshion! \n\nIn this application you can find the complementary, splitcomplementary and triad colors \n"
            "By using the following syntax: \n"
            "\tcolor\n"
            "\tcomplementary color\n"
            "\tsplitcomplementary color\n"
            "\ttriad color\n"
            "These commands will return the possible combinations. For more information type help.")
    def help():
        print("Pyshion supports colors from the primary, secundary and tertiary colors\n"
              "this include the following colors:"
              "\n\tred"
              "\tred-orange\n"
              "\torange"
              "\tyellow-orange\n"
              "\tyellow"
              "\tyellow-green\n"
              "\tgreen"
              "\tblue-green\n"
              "\tblue"
              "\tblue-violet\n"
              "\tviolet"
              "\tred-violet\n"
              "\nYou can find the complementary, splitcomplementary and triad of any of these colors."
              "\nTo find these, you just have to type in the desire action followed by the color"
              "\n\t Examples:"
              "\n\t   >>>complementary red"
              "\n\t   Output: green"
              "\n\t   >>>splitcomplementary orange"
              "\n\t   Output: blue-green and blue-violet"
              "\n\t   >>>triad blue"
              "\n\t   Output: red and yellow"
              "\n\t   >>>red"
              "\n\t   Output: the complementary is green"
              "\n\t           the splitcomplements are yellow-green and blue-green"
              "\n\t           the triads are blue and yellow"
              "\n\n ¡Enjoy making combinations with Pyshion!"

        )